---
# Default variables for VM templates

vm_templates:
  ubuntu:
    vmid: 9000
    name: "ubuntu-22.04-template"
    ostype: "l26"
    memory: 2048
    cores: 2
    disk_size: "20G"
    storage: "local"
    iso_url: "https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img"
    iso_name: "ubuntu-22.04-cloudimg-amd64.img"
    cloud_init: true
    
  debian:
    vmid: 9001
    name: "debian-12-template"
    ostype: "l26"
    memory: 2048
    cores: 2
    disk_size: "20G"
    storage: "local"
    iso_url: "https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-generic-amd64.qcow2"
    iso_name: "debian-12-generic-amd64.qcow2"
    cloud_init: true

# Cloud-init user configuration
cloud_init_user: "admin"
cloud_init_password: "changeme123"
cloud_init_ssh_keys: []

# Template storage settings
template_storage: "local"
iso_storage: "local"