---
- name: Setup Proxmox Network Bridges
  hosts: proxmox
  become: yes
  vars_files:
    - ../group_vars/proxmox.yml
  
  tasks:
    - name: Check current network configuration
      shell: ip addr show
      register: current_interfaces
      changed_when: false
      
    - name: Backup current network configuration
      copy:
        src: /etc/network/interfaces
        dest: /etc/network/interfaces.backup.{{ ansible_date_time.epoch }}
        backup: yes
        
    - name: Install bridge utilities
      apt:
        name: bridge-utils
        state: present
        update_cache: yes
        
    - name: Generate network interfaces configuration
      template:
        src: ../files/interfaces.j2
        dest: /etc/network/interfaces
        backup: yes
      notify: restart networking
      
    - name: Enable IP forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present
        reload: yes
        
    - name: Enable IPv6 forwarding
      sysctl:
        name: net.ipv6.conf.all.forwarding
        value: '1'
        state: present
        reload: yes
        
    - name: Install iptables-persistent
      apt:
        name: iptables-persistent
        state: present
        
    - name: Configure NAT rules
      iptables:
        table: nat
        chain: POSTROUTING
        source: "{{ item }}"
        out_interface: "{{ public_interface }}"
        jump: MASQUERADE
        comment: "NAT for {{ item }}"
      with_items: "{{ nat_networks }}"
      notify: save iptables
      
    - name: Allow forwarding for NAT networks
      iptables:
        chain: FORWARD
        source: "{{ item }}"
        jump: ACCEPT
        comment: "Forward {{ item }}"
      with_items: "{{ nat_networks }}"
      notify: save iptables
      
    - name: Allow established connections
      iptables:
        chain: FORWARD
        ctstate: ESTABLISHED,RELATED
        jump: ACCEPT
        comment: "Allow established connections"
      notify: save iptables
      
  handlers:
    - name: restart networking
      service:
        name: networking
        state: restarted
        
    - name: save iptables
      shell: |
        iptables-save > /etc/iptables/rules.v4
        ip6tables-save > /etc/iptables/rules.v6